name: 'bing image'

on:
  push:
  schedule:
    - cron: '*/10 * * * *'


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls
        run : ls -al
      - name: mozjpeg install
        run:  |
          TEMP_DEB="$(mktemp)" &&
          wget -O "$TEMP_DEB" 'https://github.com/aburrido/mozjpeg/releases/download/3.3.1/mozjpeg_3.3.1_amd64.deb' &&
          sudo dpkg -i "$TEMP_DEB"
          rm -f "$TEMP_DEB"
      - name: Download
        run:  |
          php bing.php de-DE
          php bing.php en-AU
          php bing.php en-CA
          php bing.php en-GB
          php bing.php en-IN
          php bing.php en-US
          php bing.php fr-CA
          php bing.php fr-FR
          php bing.php ja-JP
          php bing.php zh-CN
      - name: ls
        run : ls -al
      - name: Commit
        run: |
          if [ -n "$(git status -s)" ];then
          git config --global user.name 'aburrido'
          git config --global user.email 'aburrido@qq.com'
          git add .
          git commit -m $(date +"%Y-%m-%d.%H:%M:%S")
          git push
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/zh-CN.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/en-CA.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/en-GB.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/en-IN.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/en-US.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/fr-CA.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/fr-FR.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/ja-JP.jpg' --output /dev/null
          curl 'https://cdn.jsdelivr.net/gh/aburrido/bing@latest/zh-CN.jpg' --output /dev/null
          fi
